version: "3"
services:
    redis:
        image: redis:alpine

    unapy:
        image: unapy
        build:
            context: packages
            dockerfile: ./unapy/Dockerfile
        volumes:
            - ./packages/unapy/src:/usr/src/app/src
        environment:
            REDIS_HOST: redis 
        env_file:
            - ./packages/unapy/.env
        ports:
            - 5000:5000
        links:
            - redis
        depends_on: 
            - redis

    unoenty:
        image: unoenty
        build:
            context: packages
            dockerfile: ./unoenty/Dockerfile
        stdin_open: true
        volumes:
            - ./packages/unoenty/src:/usr/src/app/src
            - ./packages/unoenty/public:/usr/src/app/public
        env_file:
            - ./packages/unoenty/.env
        ports:
            - 80:80
        depends_on:
            - unapy